# Persistent Volume Claims
# ======================================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: taly-acs-core-api-conf-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
  volumeName: taly-acs-api-conf-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: taly-acs-core-api-logs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
  volumeName: taly-acs-api-logs-pv
---
# ======================================
# ======================================
# Deployment
# ======================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taly-acs-core-api
  labels:
    app: taly-acs-core-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taly-acs-core-api
  template:
    metadata:
      labels:
        app: taly-acs-core-api
    spec:
      containers:
        - name: taly-acs-core-api
          image: 192.168.159.240:5000/taly-acs-core-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083

          # Point Spring Boot to external logback config
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Dlogging.config=/opt/taly/conf/logback-spring.xml"

          volumeMounts:
            - name: conf
              mountPath: /opt/taly/conf
            - name: logs
              mountPath: /opt/taly/logs

      volumes:
        - name: conf
          persistentVolumeClaim:
            claimName: taly-acs-core-api-conf-pvc
        - name: logs
          persistentVolumeClaim:
            claimName: taly-acs-core-api-logs-pvc

---
# ======================================
# Service
# ======================================
apiVersion: v1
kind: Service
metadata:
  name: taly-acs-core-api-svc
spec:
  selector:
    app: taly-acs-core-api
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP

